apiVersion: v1
kind: Service
metadata:
  labels:
    app: vaulty-python
  name: vaulty-python
spec:
  ports:
  - name: "3000"
    port: 3000
    protocol: TCP
    targetPort: http
  selector:
    app: vaulty-python
  type: ClusterIP
status:
  loadBalancer: {}
